# Dataframe Drills: Characterizing a Data Frame

Different machine learning ( ML ) algorithms have many overlapping requirements and also several different requirements of the data.  For example, all ML algorithms require that none of the features have null values.  And many ML algorithms require that continuous variables be normally distributed.  Therefore, it is necessary to identify which features have nulls ( and address the nulls ) and which feature are continuous.  This exercise provides practice in characterizing a data frame.

The variable `dict_df` is a dictionary containing several data frames as values with keys named `df_001`, `df_002`, `df_003`, etc.

Your list of tasks:
1. determine the number of rows and columns in the data frame
1. determine the number of each data type in the data frame, i.e how many columns are float, integer, object, etc.
1. for each numerical column, determine some descriptive statistics, e.g the count, the minimum, the maximum, and the median
1. determine the number of nulls in each column

The process:
1. Copy this notebook to a new notebook and pin it with a name.  This will be your baseline copy.
1. Initially, work on each data frame in order, i.e. `df_001`, `df_002`, `df_003`, etc.  Later, you can randomly pick the data frames you wish to work on.
1. Keep track of how many data frames that you can do in five minutes.  This is called a run.
1. Initially, focus on only one task as you go through the run.  For example, only do task #2 during the first run.  Then only do task #3 during the second run.  And so on. Eventually, try to do all tasks on a data frame in a run.

---

**Bonus Tasks**:

Categorical variables ( i.e. nominal or ordinal ) are often tricky to identify because they could be one of a few different data types.
1. for each integer column, determine if it is nominal, ordinal, or discrete ( which is indistinguishable from any nominals or ordinals that have been encoded. )
1. for each object column, determine if it is nominal or ordinal.

**Extra Bonus Tasks** :

1. write a for-loop to automate any or all of the above tasks.
1. write a function or functions to automate any or all of the above tasks.
1. add any functions to your data science toolkit module on GitHub.

---

## Setup

In [1]:
# @title Create the dictionary of data frames.
import pandas as pd
import numpy as np

# Read in main data frame
url = "https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv"
df_all = pd.read_csv( url )

# Create a dictionary of data frames
dict_df = {}
np.random.seed(42)
i = 0
dict_df[f"df_{i:03}"] = df_all.sample( n=10 ).sample( n=10, axis = "columns" )
for i in range(1,51):
  row_pick = max( min(200, 0.1 * df_all.shape[0]), 100 )
  nrows = np.random.choice( range( 10, row_pick ) )
  ncols = np.random.choice( range( max( 10, df_all.shape[1] ) ) )
  dict_df[f"df_{i:03}"] = df_all.sample( n=nrows ).sample( n=ncols, axis = "columns" )

# for k, df in df_dict.items():
#   print( k, df.shape )

### Show keys to dictionary

In [2]:
list( dict_df.keys() )[:10]

['df_000',
 'df_001',
 'df_002',
 'df_003',
 'df_004',
 'df_005',
 'df_006',
 'df_007',
 'df_008',
 'df_009']

In [3]:
len( dict_df.keys() )

51

## Example

Determining the number of rows and columns.

In [4]:
my_df = dict_df["df_000"]
my_df.shape

(10, 10)

<br />
<br />
Determine the number of each data type in the data frame, i.e how many columns are float, integer, object, etc.

In [5]:
my_df = dict_df["df_000"]
my_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 2297 to 124
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Exter Qual     10 non-null     object
 1   Fence          1 non-null      object
 2   Roof Matl      10 non-null     object
 3   Bedroom AbvGr  10 non-null     int64
 4   Heating QC     10 non-null     object
 5   Mas Vnr Area   10 non-null     float64
 6   Fireplaces     10 non-null     int64
 7   MS SubClass    10 non-null     int64
 8   Lot Config     10 non-null     object
 9   Lot Shape      10 non-null     object
dtypes: float64(1), int64(3), object(6)
memory usage: 880.0+ bytes

<br />
<br />
For each numerical column, determine some descriptive statistics, e.g the count, the minimum, the maximum, and the median

In [6]:
my_df = dict_df["df_000"]
my_df.describe()

       Bedroom AbvGr  Mas Vnr Area  Fireplaces  MS SubClass
count      10.000000     10.000000   10.000000     10.00000
mean        2.700000    179.600000    0.700000     65.00000
std         0.948683    297.041411    0.674949     50.16639
min         1.000000      0.000000    0.000000     20.00000
25%         2.000000      0.000000    0.000000     27.50000
50%         3.000000      0.000000    1.000000     60.00000
75%         3.000000    251.500000    1.000000     60.00000
max         4.000000    922.000000    2.000000    180.00000

<br />
<br />
Determine the number of nulls in each column

In [7]:
my_df = dict_df["df_000"]
my_df.isna().sum()

Exter Qual       0
Fence            9
Roof Matl        0
Bedroom AbvGr    0
Heating QC       0
Mas Vnr Area     0
Fireplaces       0
MS SubClass      0
Lot Config       0
Lot Shape        0
dtype: int64

## Your turn